services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  spring:
    depends_on:
      - db
    image: 'openjdk:latest'
    container_name: back-end-server
    ports:
      - "8080:8080"
    volumes:
      - ./SpringApp:/javaSource
    command: sh -c "cd /javaSource; ./mvnw spring-boot:run"
    node:
      depends_on:
        - back-end
      image: 'node'
      container_name: front-end-server
      volumes:
        - ./frontend/react-app:/frontend
      ports:
        - "3000:3000"
      command: sh -c "cd /frontend ; npm run start"